// Curated English idea summaries for papers whose database entry has no description.
window.PAPER_IDEAS = {
  "Twisting Lids Off with Two Hands": "Models threaded lids with a fast brake-based simulator and trains a bimanual RL policy with twist, pose, and contact objectives. Its key contribution is encoding the fingertip contact structure needed to stabilize the bottle while rotating the lid.",
  "Visual Dexterity: In-hand Reorientation of Novel and Complex Object Shapes": "Trains a privileged state policy in simulation, then distills it into a policy that acts directly from depth point clouds. This avoids object-specific pose estimation and enables continuous in-air reorientation of unseen, irregular shapes.",
  "DeXtreme: Transfer of Agile In-hand Manipulation from Simulation to Reality": "Combines aggressive domain randomization, a recurrent control policy, and markerless RGB pose estimation for real-world Allegro-hand reorientation. The contribution is a reproducible sim-to-real system built from substantially cheaper sensing and hardware than earlier Shadow Hand setups.",
  "Sequential Dexterity: Chaining Dexterous Policies for Long-Horizon Manipulation": "Chains separately trained dexterous skills using a learned transition-feasibility function. Backward fine-tuning makes earlier policies terminate in states that later policies can actually recover from, rather than merely connecting successful subskills.",
  "Bimanual Dexterity for Complex Tasks (Bidex)": "Introduces a portable bimanual teleoperation system that tracks arms with teacher robots and fingers with motion-capture gloves. It targets accurate, low-latency collection of high-DoF demonstrations without camera-based hand tracking or an expensive external mocap room.",
  "Learning Dexterous In-Hand Manipulation": "Uses large-scale domain randomization, recurrent policies, and distributed RL to transfer in-hand object reorientation from simulation to a physical Shadow Hand. Memory lets the policy implicitly infer unobserved dynamics online instead of relying on precise system identification.",
  "Solving Rubik's Cube with a Robot Hand": "Pairs a recurrent hand policy with planner-provided flip and face-rotation subgoals, then transfers it with Automatic Domain Randomization. ADR expands the simulation distribution as training improves, producing robust long-horizon behavior and implicit online adaptation.",
  "Dexterous Manipulation with Deep RL: Efficient, General, and Low-Cost": "Learns valve rotation, box flipping, and door opening directly on inexpensive real hardware with model-free RL. Demonstration-augmented policy gradients reduce exploration cost without requiring a simulator or a manually identified dynamics model.",
  "DexterityGen: Foundation Controller for Unprecedented Dexterity": "Uses RL to generate a broad dataset of reusable low-level dexterous behaviors, then distills them into a generative foundation controller. The controller converts coarse commands from a human or another policy into stable, fine-grained hand actions.",
  "ManipTrans: Efficient Dexterous Bimanual Manipulation Transfer via Residual Learning": "Pretrains a general motion imitator from human hand trajectories and learns a small task-specific residual for contact and object dynamics. Separating kinematic imitation from physical correction makes bimanual skill transfer more sample-efficient across hands and tasks.",
  "DexMachina: Functional Retargeting for Bimanual Dexterous Manipulation": "Retargets the demonstrated object trajectory rather than copying human joint motion. Virtual object controllers initially move the articulated object and gradually decay, giving the RL policy a structured handoff from guided motion to fully autonomous contact-rich manipulation.",
  "AsymDex: Asymmetry and Relative Coordinates for RL-based Bimanual Dexterity": "Assigns a facilitating role to one hand and a dominant manipulation role to the other, then expresses coordination in an object-relative frame. These structural choices reduce the observation and action spaces instead of relying on additional reward shaping."
};
