// Curated English idea summaries for papers whose database entry has no description.
window.PAPER_IDEAS = {
  "Twisting Lids Off with Two Hands": "Models threaded lids with a fast brake-based simulator and trains a bimanual RL policy with twist, pose, and contact objectives. Its key contribution is encoding the fingertip contact structure needed to stabilize the bottle while rotating the lid.",
  "Visual Dexterity: In-hand Reorientation of Novel and Complex Object Shapes": "Trains a privileged state policy in simulation, then distills it into a policy that acts directly from depth point clouds. This avoids object-specific pose estimation and enables continuous in-air reorientation of unseen, irregular shapes.",
  "DeXtreme: Transfer of Agile In-hand Manipulation from Simulation to Reality": "Combines aggressive domain randomization, a recurrent control policy, and markerless RGB pose estimation for real-world Allegro-hand reorientation. The contribution is a reproducible sim-to-real system built from substantially cheaper sensing and hardware than earlier Shadow Hand setups.",
  "Sequential Dexterity: Chaining Dexterous Policies for Long-Horizon Manipulation": "Chains separately trained dexterous skills using a learned transition-feasibility function. Backward fine-tuning makes earlier policies terminate in states that later policies can actually recover from, rather than merely connecting successful subskills.",
  "Bimanual Dexterity for Complex Tasks (Bidex)": "Introduces a portable bimanual teleoperation system that tracks arms with teacher robots and fingers with motion-capture gloves. It targets accurate, low-latency collection of high-DoF demonstrations without camera-based hand tracking or an expensive external mocap room.",
  "Learning Dexterous In-Hand Manipulation": "Uses large-scale domain randomization, recurrent policies, and distributed RL to transfer in-hand object reorientation from simulation to a physical Shadow Hand. Memory lets the policy implicitly infer unobserved dynamics online instead of relying on precise system identification.",
  "Solving Rubik's Cube with a Robot Hand": "Pairs a recurrent hand policy with planner-provided flip and face-rotation subgoals, then transfers it with Automatic Domain Randomization. ADR expands the simulation distribution as training improves, producing robust long-horizon behavior and implicit online adaptation.",
  "Dexterous Manipulation with Deep RL: Efficient, General, and Low-Cost": "Learns valve rotation, box flipping, and door opening directly on inexpensive real hardware with model-free RL. Demonstration-augmented policy gradients reduce exploration cost without requiring a simulator or a manually identified dynamics model.",
  "DexterityGen: Foundation Controller for Unprecedented Dexterity": "Uses RL to generate a broad dataset of reusable low-level dexterous behaviors, then distills them into a generative foundation controller. The controller converts coarse commands from a human or another policy into stable, fine-grained hand actions.",
  "ManipTrans: Efficient Dexterous Bimanual Manipulation Transfer via Residual Learning": "Pretrains a general motion imitator from human hand trajectories and learns a small task-specific residual for contact and object dynamics. Separating kinematic imitation from physical correction makes bimanual skill transfer more sample-efficient across hands and tasks.",
  "DexMachina: Functional Retargeting for Bimanual Dexterous Manipulation": "Retargets the demonstrated object trajectory rather than copying human joint motion. Virtual object controllers initially move the articulated object and gradually decay, giving the RL policy a structured handoff from guided motion to fully autonomous contact-rich manipulation.",
  "AsymDex: Asymmetry and Relative Coordinates for RL-based Bimanual Dexterity": "Assigns a facilitating role to one hand and a dominant manipulation role to the other, then expresses coordination in an object-relative frame. These structural choices reduce the observation and action spaces instead of relying on additional reward shaping.",
  "Dexterous Manipulation through Imitation Learning: A Survey": "Organizes dexterous imitation learning around demonstration acquisition, motion representation and retargeting, policy learning, and deployment. Its value is a unified view of where data quality, embodiment mismatch, contact dynamics, and generalization enter the pipeline.",
  "Interactive Imitation Learning for Dexterous Robotic Manipulation: A Survey": "Reviews real-world dexterous learning through the lens of limited demonstrations and covariate shift, then positions interactive imitation learning as the missing feedback loop. It distinguishes how human corrections, interventions, and preferences can refine a policy after the initial demonstration set.",
  "A Scalable Platform for Robot Learning and Physical Skill Data Collection": "Introduces PD.RAI, a parallel and distributed platform that connects robot-learning units, data storage, and remote operators across heterogeneous hardware. The system is designed to pool otherwise idle robots and scale collection of force-controlled, contact-rich skills under a common interface.",
  "Augmentation Enables One-Shot Generalization in LfD for Contact-Rich Manipulation": "Starts from one human demonstration, then lets the robot purposefully interact with the mechanism to augment that trajectory. The added local experience makes the learned controller robust to pose and mechanism variations without asking for more expert demonstrations.",
  "AutoRT: Embodied Foundation Models for Large Scale Orchestration of Robotic Agents": "Uses a vision-language model to propose and score context-appropriate tasks while a robot policy executes them behind explicit safety filters. The contribution is a fleet orchestration system that turns foundation-model reasoning into large-scale, minimally supervised real-world robot data collection.",
  "Coarse-to-Fine Imitation Learning: Robot Manipulation from a Single Demonstration": "Splits a task into a coarse approach to a learned interaction bottleneck and a fine trajectory copied from the demonstration. Self-supervised camera motion trains the bottleneck estimator, allowing one-shot learning without fitting an end-to-end policy for the contact phase.",
  "Data Scaling Laws in Imitation Learning for Robotic Manipulation": "Systematically varies demonstration quantity, object and environment diversity, and model scale to measure how imitation policies improve. It turns the vague prescription to collect more data into empirical scaling relationships and identifies diversity as essential for zero-shot deployment.",
  "DexScale: Automating Data Scaling for Sim2Real Generalizable Robot Control": "Builds a data engine that turns a human video into a scalable simulated robot-skill dataset, while inserting realistic visual and semantic information to reduce the domain gap. Policies are trained at simulation scale and adapted for deployment without collecting a large real-robot dataset.",
  "The Ingredients of Real-World Robotic Reinforcement Learning": "Assembles the practical components needed for unattended physical RL: example-based rewards, autonomous reset behaviors, demonstrations, and off-policy learning. The paper's contribution is showing how these ingredients interact as a continuous system rather than treating the RL algorithm as the only bottleneck.",
  "Learning Hand-Eye Coordination for Robotic Grasping with Large-Scale Data Collection": "Learns an action-conditioned grasp-success predictor from more than 800,000 physical attempts collected by a robot fleet. Repeatedly querying that model turns monocular images directly into closed-loop gripper motion, avoiding camera calibration and explicit object pose estimation.",
  "End-to-End Training of Deep Visuomotor Policies": "Uses guided policy search to convert trajectory-centric reinforcement learning into supervised training of a convolutional policy from pixels to motor torques. Jointly learning perception and control removes the hand-engineered vision and state-estimation stack used by earlier manipulation systems.",
  "MT-Opt: Continuous Multi-Task Robotic RL at Scale": "Shares data, representations, and exploration across a continually growing set of robot tasks, with task rewards specified through examples of desired outcomes. Its multi-task Q-learning formulation lets new skills bootstrap from previously collected experience instead of starting a separate RL run.",
  "Reset-Free Reinforcement Learning via Multi-Task Learning (MTRF)": "Treats reset behaviors as useful tasks within the same multi-task RL problem. Forward and reverse skills continually place the environment into states that train one another, enabling long autonomous practice without a manually engineered reset mechanism.",
  "OPTIMUS: Imitating Task and Motion Planning with Visuomotor Transformers": "Uses a task-and-motion planner as an automatic expert that produces large, diverse demonstrations, then distills those plans into a visuomotor Transformer. This combines the compositional supervision of planning with the fast image-to-action execution of a learned policy.",
  "Supersizing Self-Supervision: Learning to Grasp from 50K Tries and 700 Robot Hours": "Scales physical trial-and-error grasp collection far beyond prior datasets and learns grasp selection as classification over image patches. Multi-stage hard-negative mining focuses later collection on the model's mistakes, improving unseen-object generalization without human grasp labels.",
  "QT-Opt: Scalable Deep RL for Vision-Based Robotic Manipulation": "Trains a large off-policy Q-function from more than 580,000 real grasp attempts and optimizes continuous actions online. Unlike one-shot grasp detectors, it produces closed-loop behaviors such as probing, repositioning, regrasping, and recovery from disturbances.",
  "Real2Render2Real: Scaling Robot Data Without Dynamics Simulation or Robot Hardware": "Extracts object motion from a monocular human demonstration, combines it with a smartphone object scan, and renders diverse robot observation-action pairs. It scales visually grounded imitation data without contact simulation, teleoperation, or access to the physical robot during collection.",
  "RoboCat: A Self-Improving Generalist Agent for Robotic Manipulation": "Trains one visual goal-conditioned Transformer across multiple tasks, observation spaces, action spaces, and robot embodiments. It adapts to a new task from 100–1,000 examples and then adds its own successful rollouts back into training, forming a basic self-improvement loop.",
  "Sample Efficient Grasp Learning Using Equivariant Models": "Encodes the planar grasp problem's SE(2) symmetry directly in an equivariant convolutional network. The inductive bias reduces physical data needs to roughly 600 attempts, making online learning from scratch feasible on one robot in about 1.5 hours.",
  "Self-Improving Robots: End-to-End Autonomous Visuomotor RL (MEDAL++)": "Learns both a visual reward and policies that do and undo a task from a small seed set of demonstrations. Alternating the forward and backward behaviors supplies autonomous resets, allowing continued real-world practice with little supervision.",
  "Robot Learning on the Job: Human-in-the-Loop Autonomy During Deployment (Sirius)": "Lets an autonomous policy handle routine decisions while a remote human intervenes only at failure-prone moments. Those interventions become targeted training data, so deployment simultaneously provides useful service and improves the policy where its distribution shift is largest.",
  "So You Think You Can Scale Up Autonomous Robot Data Collection?": "Stress-tests autonomous imitation-learning pipelines under realistic scaling conditions and finds that they inherit reset, success-detection, and environment-design burdens commonly associated with RL. Its contribution is a diagnostic study showing where apparent autonomy breaks down rather than another collection algorithm.",
  "Working Backwards: Learning to Place by Picking": "Generates contact-rich placement demonstrations by starting objects in their desired poses, executing autonomous picks, and reversing the resulting trajectories. This pick-to-place symmetry replaces repeated human teleoperation with scalable physical data collection.",
  "Being-H0: Vision-Language-Action Pretraining from Large-Scale Human Videos": "Treats human hands as a scalable foundation manipulator and pretrains a VLA on curated mocap, VR, and RGB video. Physical instruction tuning, 3D alignment, and part-level motion tokens turn that human motion prior into precise robot-manipulation behavior.",
  "Large Video Planner Enables Generalizable Robot Control": "Uses a video foundation model to generate a visual plan of how a task should unfold, then retargets the predicted hand motion for robot execution. History guidance, diffusion forcing, and internet-scale video pretraining make temporal prediction—not direct action-token prediction—the generalization mechanism.",
  "RealDex: Towards Human-like Grasping for Robotic Dexterous Hand": "Introduces a multi-view, multimodal dataset of teleoperated grasps that preserves human-like wrist and finger motion rather than only terminal grasp poses. A learned motion-generation framework uses this data to synthesize natural, collision-aware dexterous grasp trajectories.",
  "DexCap: Scalable Portable Mocap Data Collection for Dexterous Manipulation": "Combines SLAM-based wrist tracking, electromagnetic finger tracking, and 3D scene observations in a portable capture system. DexIL then learns robot skills directly from the resulting human hand trajectories, separating data collection from slow, embodiment-specific robot teleoperation.",
  "DROID: A Large-Scale In-The-Wild Robot Manipulation Dataset": "Standardizes a portable robot stack and collection protocol so 50 operators can gather 76,000 demonstrations across 564 scenes and 86 tasks. The key contribution is environmental and operator diversity at distributed scale, together with evidence that it improves policy generalization.",
  "Mobile ALOHA: Bimanual Mobile Manipulation with Low-Cost Whole-Body Teleoperation": "Extends ALOHA with a mobile base and a whole-body bilateral teleoperation interface for tasks coupling navigation and two-arm manipulation. Co-training on existing stationary ALOHA data substantially improves the mobile behavior-cloning policies.",
  "RH20T: A Comprehensive Robotic Dataset for Learning Diverse Skills in One-Shot": "Collects diverse manipulation skills with synchronized vision, robot state, force, audio, and tactile-related signals across multiple robot platforms. Its focus is rich-contact, multimodal one-shot transfer rather than another large set of visually guided pick-and-place trajectories.",
  "RoboTurk: A Crowdsourcing Platform for Robotic Skill Learning through Imitation": "Turns commodity smartphones into 6-DoF teleoperation devices and supports remote demonstration collection under network latency. The platform showed that non-expert crowds could produce thousands of long-horizon demonstrations without specialized VR hardware.",
  "MANUS: Markerless Grasp Capture using Articulated 3D Gaussians": "Represents the hand and object with articulated 3D Gaussians to recover detailed, markerless grasps and more accurate contact than skeleton or parametric-mesh capture. It also contributes MANUS-Grasps, a multi-view dataset containing more than seven million frames.",
  "ALOHA Unleashed: A Simple Recipe for Robot Dexterity": "Shows how far pure imitation learning can go when both demonstrations and model capacity are scaled: more than 26,000 ALOHA 2 episodes train a large Transformer with a diffusion action head. The recipe handles contact-rich, multimodal tasks such as shoelace tying and robot self-repair without RL or task-specific controllers.",
  "mimic-one: a Scalable Model Recipe for General Purpose Robot Dexterity": "Co-designs a 16-DoF tendon-driven hand, glove/Vision Pro teleoperation, and a diffusion policy with long action chunks. Systematic variation and deliberately recorded recovery trajectories yield smooth fine-motor behavior and emergent self-correction from a few thousand demonstrations.",
  "Towards a Generalizable Bimanual Foundation Policy via Flow-based Video Prediction": "Repurposes a pretrained text-to-video model as a bimanual planner, decomposing prediction into text-to-optical-flow and flow-to-video stages. The intermediate motion field reduces language ambiguity and physical hallucination before a lightweight diffusion policy extracts dual-arm actions.",
  "Bunny-VisionPro: Real-Time Bimanual Dexterous Teleoperation for Imitation Learning": "Maps Vision Pro hand tracking to two dexterous robot hands with fast loop-joint retargeting, collision avoidance, and low-cost fingertip haptic feedback. The system contribution is not just teleoperation latency: its safer, more immersive demonstrations measurably improve several downstream imitation policies.",
  "Dynamic Handover: Throw and Catch with Bimanual Hands": "Formulates throwing and catching as a cooperative multi-agent RL problem for two arm-hand systems. A learned flight-trajectory predictor lets the catching hand act ahead of the observed object, enabling high-speed sim-to-real handovers rather than quasi-static exchanges.",
  "HumanoidGen: Data Generation for Bimanual Dexterous Manipulation via LLM Reasoning": "Uses spatially annotated assets and reusable atomic operations so an LLM can generate collision-aware relational constraints for two arms. A tree-search procedure repairs long-horizon plans, producing scalable simulation demonstrations for training 2D and 3D diffusion policies.",
  "AnyBimanual: Transferring Unimanual Policy for General Bimanual Manipulation": "Adapts an arbitrary pretrained single-arm policy instead of learning bimanual behavior from scratch. A skill manager schedules reusable unimanual primitives while a visual aligner masks each arm's relevant workspace, requiring only a small bimanual demonstration set.",
  "PerAct2: Benchmarking and Learning for Robotic Bimanual Manipulation Tasks": "Extends RLBench with tasks categorized by the kind of two-arm coordination they require, then introduces a language-conditioned voxel policy for the benchmark. One Perceiver backbone shares attention between arm-specific latent regions and predicts both arms' actions jointly.",
  "VoxAct-B: Voxel-Based Acting and Stabilizing Policy for Bimanual Manipulation": "Targets asymmetric tasks by explicitly separating an acting arm from a stabilizing arm. A vision-language model crops the voxel workspace around the relevant object, increasing effective spatial resolution before two role-specific PerAct policies predict coordinated actions.",
  "AnyDexGrasp: General Dexterous Grasping for Different Hands with Human-level Learning Efficiency": "Separates hand-independent scene understanding from embodiment-specific control: a universal model predicts contact-centric grasp representations, then a small decision model is learned for each hand. Reusing the geometric representation cuts adaptation to hundreds of physical attempts across very different hand morphologies.",
  "DexGrasp Anything: Towards Universal Robotic Dexterous Grasping with Physics Awareness": "Adds surface attraction, object-penetration, and self-penetration constraints to both diffusion training and sampling. Geometry is fused with language-generated object semantics, allowing the grasp generator to improve physical feasibility and choose meaningful regions across diverse objects.",
  "RobustDexGrasp: Robust Dexterous Grasping of General Objects from Single-view Perception": "Represents shape through dynamic distances from finger joints to the object, focusing the policy on hand-relevant local geometry. A privileged visual-tactile teacher is distilled and then refined with RL into a student that uses one noisy point cloud yet adapts to disturbances during execution.",
  "DexGraspNet 2.0: Learning Generative Dexterous Grasping in Large-scale Synthetic Cluttered Scenes": "Introduces a cluttered-scene benchmark with 427 million grasps and a two-stage generator whose diffusion model conditions on local geometry. Test-time depth restoration bridges corrupted real sensing, enabling zero-shot transfer instead of retraining the grasp model on physical data.",
  "BODex: Scalable and Efficient Robotic Dexterous Grasp Synthesis Using Bilevel Optimization": "Formulates grasp synthesis as bilevel optimization: a lower-level quadratic program solves contact forces while upper-level gradient descent updates the grasp. GPU-parallel QP makes high-quality, low-penetration data generation fast enough to build datasets and a common MuJoCo benchmark across several hands.",
  "DexVLG: Dexterous Vision-Language-Grasp Model at Scale": "Couples a vision-language model with a flow-matching pose head to grasp the semantic object part named in an instruction from one RGB-D view. Its enabling asset is DexGraspNet 3.0, which pairs 170 million part-aligned grasps with captions across 174,000 objects.",
  "EgoDex: Learning Dexterous Manipulation from Large-Scale Egocentric Video": "Uses Vision Pro to collect 829 hours of egocentric video with synchronized 3D hand and upper-body pose at capture time. It turns passive human activity into action-labeled data and benchmarks behavior cloning, diffusion, and flow matching for future hand motion and goal-conditioned inverse dynamics.",
  "HUG: Human Universal Grasping": "Trains a point-conditioned flow-matching model entirely on one million natural human grasp observations rather than robot demonstrations or simulation. Predicted MANO grasps are retargeted to different anthropomorphic robot hands, giving cross-embodiment and in-the-wild deployment without per-hand retraining.",
  "ENPIRE: Agentic Robot Policy Self-Improvement in the Real World": "Gives coding agents control of the complete physical learning loop: reset, literature search, implementation, rollout, verification, failure analysis, and policy revision. The distinctive contribution is letting the agent design tests and improve algorithms across a real robot fleet, not merely tune a reward in simulation.",
  "SAM 3: Segment Anything with Concepts": "Extends visual point and box prompts with open-vocabulary noun phrases and image exemplars, segmenting every matching instance in images or video. A shared detector-tracker backbone and a separate presence head decouple recognizing whether a concept exists from localizing it.",
  "D-Grasp: Physically Plausible Dynamic Grasp Synthesis for Hand-Object Interactions": "Introduces dynamic grasp synthesis, where a hand must approach, grasp, and carry an object to a target 6D pose rather than produce a static contact pose. Hierarchical RL separates low-level grasp maintenance from high-level motion and can physically correct imperfect reference labels.",
  "GraspXL: Generating Grasping Motions for Diverse Objects at Scale": "Trains one policy to satisfy composable objectives for grasp region, approach heading, wrist rotation, and hand position across object and hand morphologies. It needs no captured 3D interaction data and scales from 58 training objects to motion generation for more than 500,000 unseen objects.",
  "Learning Human-to-Robot Handovers from Point Clouds": "Uses a two-stage teacher-student pipeline to avoid requiring a real human during every policy rollout. A teacher combines motion and grasp planning with RL in simulation, while self-supervision distills the behavior into a point-cloud policy that transfers to real handovers.",
  "ArtiGrasp: Physically Plausible Synthesis of Bi-Manual Dexterous Grasping and Articulation": "Trains one physics-based policy to coordinate global wrists and local fingers for grasping, relocating, and articulating an object. Its curriculum grows from a stationary single-hand problem to two agents manipulating a movable articulated object, making precise finger learning tractable.",
  "Physically Plausible Full-Body Hand-Object Interaction Synthesis": "Learns separate latent skill priors for body and hand motion, then lets a high-level RL policy control both spaces for approach, grasp, and trajectory following. Combining task reward with adversarial motion style yields full-body interactions that remain physical without requiring paired full-body object-motion data.",
  "DiffH2O: Diffusion-Based Synthesis of Hand-Object Interactions from Textual Descriptions": "Decomposes text-driven interaction into a grasping diffusion model and a manipulation diffusion model, using a compact representation that couples hand and object pose. Target-grasp and detailed-text guidance provide independent control over how an object is acquired and what happens afterward.",
  "Omnigrasp: Grasping Diverse Objects with Simulated Humanoids": "Uses a pretrained humanoid motion representation as the motor prior for a controller that grasps and transports more than 1,200 objects along arbitrary trajectories. This avoids paired full-body/object motion data and scales with simple states and rewards despite the dexterous whole-body action space.",
  "SynH2R: Synthesizing Hand-Object Motions for Learning Human-to-Robot Handovers": "Replaces expensive human mocap with a generator designed to produce handover-friendly human grasp and approach motions. Scaling synthetic humans and objects by roughly two orders of magnitude trains handover policies competitive with methods that rely on captured motion.",
  "FunGrasp: Functional Grasping for Diverse Dexterous Hands": "Extracts the intended functional grasp from a single RGB-D image of a human, retargets it across robot hands, and uses the pose to guide an RL controller. Privileged learning and sim-to-real techniques preserve task-specific grasps on unseen objects instead of collapsing to generic power grasps.",
  "LatentHOI: On the Generalizable Hand Object Motion Generation with Latent Hand Diffusion": "Decouples high-level temporal motion from fine spatial hand-object contact using latent diffusion coupled to a grasp VAE. The regularized grasp latent ties motion to object geometry and improves single- and bimanual generation on object categories unseen during training.",
  "Demonstration-Guided Deep Reinforcement Learning of Control Policies for Dexterous Human-Robot Interaction": "Uses one parameterized multi-objective reward for handshakes, claps, and finger touches, with its weights inferred from human-human motion capture. Demonstrations shape what natural interaction looks like while RL handles the robot's arm-hand dynamics and contact.",
  "Towards Affordance-Aware Robotic Dexterous Grasping with Human-like Priors": "Freezes a grasp policy trained to imitate human hand motion, then learns a PPO residual that adapts it to object geometry while avoiding semantically inappropriate contact regions. A privileged teacher is distilled with DAgger into a point-cloud student.",
  "Learning Object-Centric Motion Priors from Human for Robotic Dexterous Manipulation": "Predicts future hand–object trajectories from human HOI data, retargets the hand motion, and uses the predicted object motion as a dense PPO reward. The unusual part is not PPO or contact shaping: object-state tracking replaces separate lift, rotate, and articulate rewards across tasks.",
  "LatentVLA: Taming Latent Space for Generalizable and Long-Horizon Bimanual Manipulation": "Learns continuous latent actions from both action-free video and labeled robot data, then generates 16-step latent plans with diffusion. Language-guided attention filters irrelevant motion, while absolute episode-time encoding distinguishes visually similar phases of a long task.",
  "Dexterous Manipulation Transfer via Progressive Kinematic-Dynamic Alignment": "Retargets human fingertips to form a primary robot trajectory, then limits RL to a residual that repairs hand–object contact near a thumb-guided pre-grasp. A separate object-relative wrist planner preserves the demonstrated manipulation after grasping.",
  "SNS-Grasp: Semantic-guided Noise Scaling for Grasp Generation": "Uses an intent classifier’s per-joint gradients to reduce diffusion noise on the fingers that matter for hold-versus-use semantics while preserving diversity elsewhere. SDF-guided refinement then repairs hand–object geometry; it generates MANO grasps rather than robot control policies."
};

// Summary pages can be attached without editing the main paper database.
window.PAPER_SUMMARIES = {
  "Multi-Keypoint Affordance Representation for Functional Dexterous Grasping": "overview/paper.html?id=multi-keypoint-affordance&from=library",
  "Towards Affordance-Aware Robotic Dexterous Grasping with Human-like Priors": "overview/afforddex.html",
  "Learning Object-Centric Motion Priors from Human for Robotic Dexterous Manipulation": "overview/paper.html?id=object-centric-motion-priors",
  "LatentVLA: Taming Latent Space for Generalizable and Long-Horizon Bimanual Manipulation": "overview/paper.html?id=latentvla",
  "Dexterous Manipulation Transfer via Progressive Kinematic-Dynamic Alignment": "overview/paper.html?id=pkda",
  "SNS-Grasp: Semantic-guided Noise Scaling for Grasp Generation": "overview/paper.html?id=sns-grasp"
};

// Metadata corrections discovered after the main database was assembled.
window.PAPER_METADATA_OVERRIDES = {
  "mimic-one: a Scalable Model Recipe for General Purpose Robot Dexterity": {
    venue: "CoRL 2025 Workshop · Spotlight"
  }
};

(window.PAPERS || []).forEach(p => {
  if (window.PAPER_METADATA_OVERRIDES[p.title]) {
    Object.assign(p, window.PAPER_METADATA_OVERRIDES[p.title]);
  }
  if (window.PAPER_SUMMARIES[p.title]) {
    p.summary = window.PAPER_SUMMARIES[p.title];
    const genericId = p.summary.match(/^overview\/paper\.html\?id=([^&]+)$/);
    if (genericId) p.image = "overview_assets/" + genericId[1] + ".png";
  }
});
